---
- name: Configure zabbix agent
  hosts: all
  tasks:
    - name: Install repo
      ansible.builtin.apt:
        #name: zabbix-release
        deb: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb
      
    - name: Install agent
      ansible.builtin.apt:
        name: zabbix-agent2
        update_cache: yes

    - name: copy config
      ansible.builtin.template:
        src: zabbix-agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: "0644"

    - name: restart service
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted
